const fs = require('fs');
const path = require('path');

const CORE_SKILLS_PATH = path.join(__dirname, '..', '..', 'core', 'skills');
const AGENTS_MD_PATH   = path.join(__dirname, '..', '..', 'AGENTS.md');

// Aider config goes to project root
const CONF_FILE        = path.join(process.cwd(), '.aider.conf.yml');
const CONVENTIONS_FILE = path.join(process.cwd(), 'CONVENTIONS.md');

/**
 * Aider adapter — export.js
 *
 * Aider uses two complementary files:
 *   1. `.aider.conf.yml`   — config file that points Aider to conventions
 *   2. `CONVENTIONS.md`    — flat Markdown with all skills compiled in
 *
 * The config tells Aider to load CONVENTIONS.md via `read:` directive and
 * pre-loads it as a read-only context file on every session.
 *
 * Format spec: https://aider.chat/docs/config/aider_conf.html
 */

function stripFrontmatter(content) {
  return content.replace(/^---[\s\S]*?---\n/, '').trimStart();
}

function extractYamlField(yamlText, field) {
  const regex = new RegExp(`^${field}:\\s*(.+)$`, 'm');
  const match = yamlText.match(regex);
  return match ? match[1].trim() : null;
}

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
  }

  if (!fs.existsSync(skillMdPath)) return null;

  const raw  = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  return `\n## Skill: ${title}\n\n${body}`;
}

function generateAiderConf() {
  const conf = `# .aider.conf.yml
# Auto-generated by: node .agents/ctx.js export aider
# Source: .agents/core/skills/  ·  Do not edit manually.

# Load project conventions as a read-only context file on every session
read:
  - CONVENTIONS.md

# Recommended model settings (override as needed)
# model: gpt-4o
# editor-model: gpt-4o-mini

# Auto-commit after every accepted change
auto-commits: true

# Show diffs in git format
pretty: true
`;
  return conf;
}

function run() {
  console.log('Starting Aider adapter export...');

  // ── 1. Write .aider.conf.yml ─────────────────────────────────────────────────
  fs.writeFileSync(CONF_FILE, generateAiderConf());
  console.log(`Generated .aider.conf.yml → ${CONF_FILE}`);

  // ── 2. Build CONVENTIONS.md ──────────────────────────────────────────────────
  const sections = [];

  sections.push(
    `# CONVENTIONS.md — ContextOS Project Conventions\n\n` +
    `> Auto-generated by: node .agents/ctx.js export aider\n` +
    `> Source: .agents/core/skills/  ·  Do not edit manually.\n\n` +
    `Aider will load this file as read-only context on every session.\n`
  );

  // Project rules
  if (fs.existsSync(AGENTS_MD_PATH)) {
    const agentsMd = fs.readFileSync(AGENTS_MD_PATH, 'utf8');
    sections.push(`\n---\n\n## Project Rules\n\n${agentsMd}`);
  }

  // Skills
  sections.push('\n---\n\n# Skills\n');
  const skills = fs.readdirSync(CORE_SKILLS_PATH);
  let count = 0;
  for (const skill of skills) {
    const fullPath = path.join(CORE_SKILLS_PATH, skill);
    if (!fs.statSync(fullPath).isDirectory()) continue;
    const section = buildSkillSection(fullPath);
    if (section) {
      sections.push(section);
      count++;
    }
  }

  fs.writeFileSync(CONVENTIONS_FILE, sections.join('\n'));
  console.log(`Generated CONVENTIONS.md (${count} skills) → ${CONVENTIONS_FILE}`);
}

module.exports = { run };
