const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter } = require('../shared.js');

// Output goes to the project root (cwd), not inside .agents/
const OUTPUT_FILE = path.join(process.cwd(), '.cursorrules');

/**
 * Cursor adapter — export.js
 *
 * Cursor reads `.cursorrules` from the project root as a flat Markdown file.
 * We compile every skill's SKILL.md (stripping YAML frontmatter) into one
 * concatenated document, preceded by the top-level AGENTS.md rules.
 *
 * Format spec: https://docs.cursor.com/context/rules-for-ai
 */

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
  }

  if (!fs.existsSync(skillMdPath)) {
    return null; // no content to include
  }

  const raw = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  return `\n## Skill: ${title}\n\n${body}`;
}

function run() {
  console.log('Starting Cursor adapter export...');

  const sections = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  sections.push(
    `# ContextOS — AI Rules for Cursor\n` +
    `# Auto-generated by: node .agents/ctx.js export cursor\n` +
    `# Source: .agents/core/skills/  ·  Do not edit manually.\n`
  );

  // ── Top-level AGENTS.md ──────────────────────────────────────────────────────
  if (fs.existsSync(AGENTS_MD_PATH)) {
    const agentsMd = fs.readFileSync(AGENTS_MD_PATH, 'utf8');
    sections.push(`\n---\n\n## Project Rules (AGENTS.md)\n\n${agentsMd}`);
  }

  // ── All skills ───────────────────────────────────────────────────────────────
  sections.push('\n---\n\n# Skills\n');
  const skills = collectSkillDirectories();
  let count = 0;
  for (const skill of skills) {
    const section = buildSkillSection(skill);
    if (section) {
      sections.push(section);
      count++;
    }
  }

  fs.writeFileSync(OUTPUT_FILE, sections.join('\n'));
  console.log(`Generated .cursorrules (${count} skills) → ${OUTPUT_FILE}`);
}

module.exports = { run };
