const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter, readMeaningfulMarkdown } = require('../shared.js');

// Output destinations for Zed
const ZED_DIR = path.join(process.cwd(), '.zed');
const RULES_FILE = path.join(ZED_DIR, 'rules.md');
const PROMPTS_DIR = path.join(ZED_DIR, 'prompts');

/**
 * Zed IDE adapter — export.js
 *
 * Generates:
 *   1. `.zed/rules.md` — Project assistant instructions loaded into Zed's context
 *   2. `.zed/prompts/*.md` — Modular slash-command prompts for Zed Assistant
 *
 * Format spec: https://zed.dev/docs/assistant
 */

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) return null;

  let raw = fs.readFileSync(skillMdPath, 'utf8');
  
  const examples = readMeaningfulMarkdown(path.join(skillDir, 'EXAMPLES.md'));
  if (examples) {
    raw += '\n\n' + examples;
  }
  
  const troubleshooting = readMeaningfulMarkdown(path.join(skillDir, 'TROUBLESHOOTING.md'));
  if (troubleshooting) {
    raw += '\n\n' + troubleshooting;
  }
  
  const body = stripFrontmatter(raw);

  const descLine = description ? `> ${description.replace(/\r?\n+/g, ' ').trim()}\n\n` : '';
  return {
    skillName,
    title,
    section: `\n### Skill: ${title}\n\n${descLine}${body}`,
    prompt: `# ContextOS — ${title}\n\n${descLine}${body}\n`,
  };
}

function run() {
  console.log('Starting Zed IDE adapter export...');

  fs.mkdirSync(ZED_DIR, { recursive: true });
  fs.mkdirSync(PROMPTS_DIR, { recursive: true });

  const lines = [];

  // ── Header ───────────────────────────────────────────────────────────────────
  lines.push(
    `# ContextOS — AI Rules for Zed Assistant\n`,
    `<!-- Auto-generated by: node .agents/ctx.js export zed -->\n`,
    `<!-- Source: .agents/core/skills/  ·  Do not edit manually. -->\n\n`
  );

  // ── Project Rules ────────────────────────────────────────────────────────────
  if (fs.existsSync(AGENTS_MD_PATH)) {
    const agentsMd = fs.readFileSync(AGENTS_MD_PATH, 'utf8');
    lines.push(`## Project Rules (AGENTS.md)\n\n${agentsMd}\n\n---\n`);

    // Also write a master prompt in .zed/prompts/contextos.md
    fs.writeFileSync(path.join(PROMPTS_DIR, 'contextos.md'), `# ContextOS Master Prompt\n\n${agentsMd}\n`);
  }

  // ── Skills ───────────────────────────────────────────────────────────────────
  lines.push(`\n## Skills Library\n`);
  lines.push(`The following specialist skills guide architecture and implementation:\n`);

  const skills = collectSkillDirectories();
  let count = 0;

  for (const skill of skills) {
    const skillData = buildSkillSection(skill);
    if (skillData) {
      lines.push(skillData.section);
      fs.writeFileSync(path.join(PROMPTS_DIR, `${skillData.skillName}.md`), skillData.prompt);
      count++;
    }
  }

  // Write master .zed/rules.md
  fs.writeFileSync(RULES_FILE, lines.join(''));
  console.log(`Generated .zed/rules.md (${count} skills) → ${RULES_FILE}`);
  console.log(`Generated .zed/prompts/*.md (${count} prompts) → ${PROMPTS_DIR}`);
}

module.exports = { run };
