const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter } = require('../shared.js');

// GitHub Copilot reads from .github/copilot-instructions.md
const OUTPUT_FILE = path.join(process.cwd(), '.github', 'copilot-instructions.md');

/**
 * GitHub Copilot adapter — export.js
 *
 * Copilot reads `.github/copilot-instructions.md` as a plain Markdown file.
 * We compile AGENTS.md + all skills into one document with clear section
 * headings so Copilot can reference them contextually.
 *
 * Format spec: https://docs.github.com/en/copilot/customizing-copilot/adding-repository-instructions
 */

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) return null;

  let raw = fs.readFileSync(skillMdPath, 'utf8');
  
  const examplesPath = path.join(skillDir, 'EXAMPLES.md');
  if (fs.existsSync(examplesPath)) {
    raw += '\n\n' + fs.readFileSync(examplesPath, 'utf8');
  }
  
  const troubleshootingPath = path.join(skillDir, 'TROUBLESHOOTING.md');
  if (fs.existsSync(troubleshootingPath)) {
    raw += '\n\n' + fs.readFileSync(troubleshootingPath, 'utf8');
  }
  
  const body = stripFrontmatter(raw);

  const descLine = description ? `> ${description}\n\n` : '';
  return `\n### ${title}\n\n${descLine}${body}`;
}

function run() {
  console.log('Starting GitHub Copilot adapter export...');

  const lines = [];

  // ── Header ───────────────────────────────────────────────────────────────────
  lines.push(
    `# GitHub Copilot Instructions — ContextOS\n`,
    `<!-- Auto-generated by: node .agents/ctx.js export copilot -->\n`,
    `<!-- Source: .agents/core/skills/  ·  Do not edit manually. -->\n\n`
  );

  // ── Project rules from AGENTS.md ─────────────────────────────────────────────
  if (fs.existsSync(AGENTS_MD_PATH)) {
    const agentsMd = fs.readFileSync(AGENTS_MD_PATH, 'utf8');
    lines.push(`## Project Rules\n\n${agentsMd}\n\n---\n`);
  }

  // ── Skills ───────────────────────────────────────────────────────────────────
  lines.push(`\n## Skills Library\n`);
  lines.push(`The following skills define specialist knowledge.\n`);
  lines.push(`Reference the relevant skill when working on a task.\n`);

  const skills = collectSkillDirectories();
  let count = 0;
  for (const skill of skills) {
    const section = buildSkillSection(skill);
    if (section) {
      lines.push(section);
      count++;
    }
  }

  // ── Write ────────────────────────────────────────────────────────────────────
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, lines.join(''));
  console.log(`Generated .github/copilot-instructions.md (${count} skills) → ${OUTPUT_FILE}`);
}

module.exports = { run };
