const fs = require('fs');
const path = require('path');

const CORE_SKILLS_PATH = path.join(__dirname, '..', '..', 'core', 'skills');
const AGENTS_MD_PATH   = path.join(__dirname, '..', '..', 'AGENTS.md');

// GitHub Copilot reads from .github/copilot-instructions.md
const OUTPUT_FILE = path.join(process.cwd(), '.github', 'copilot-instructions.md');

/**
 * GitHub Copilot adapter — export.js
 *
 * Copilot reads `.github/copilot-instructions.md` as a plain Markdown file.
 * We compile AGENTS.md + all skills into one document with clear section
 * headings so Copilot can reference them contextually.
 *
 * Format spec: https://docs.github.com/en/copilot/customizing-copilot/adding-repository-instructions
 */

function stripFrontmatter(content) {
  return content.replace(/^---[\s\S]*?---\n/, '').trimStart();
}

function extractYamlField(yamlText, field) {
  const regex = new RegExp(`^${field}:\\s*(.+)$`, 'm');
  const match = yamlText.match(regex);
  return match ? match[1].trim() : null;
}

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) return null;

  const raw  = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  const descLine = description ? `> ${description}\n\n` : '';
  return `\n### ${title}\n\n${descLine}${body}`;
}

function run() {
  console.log('Starting GitHub Copilot adapter export...');

  const lines = [];

  // ── Header ───────────────────────────────────────────────────────────────────
  lines.push(
    `# GitHub Copilot Instructions — ContextOS\n`,
    `<!-- Auto-generated by: node .agents/ctx.js export copilot -->\n`,
    `<!-- Source: .agents/core/skills/  ·  Do not edit manually. -->\n\n`
  );

  // ── Project rules from AGENTS.md ─────────────────────────────────────────────
  if (fs.existsSync(AGENTS_MD_PATH)) {
    const agentsMd = fs.readFileSync(AGENTS_MD_PATH, 'utf8');
    lines.push(`## Project Rules\n\n${agentsMd}\n\n---\n`);
  }

  // ── Skills ───────────────────────────────────────────────────────────────────
  lines.push(`\n## Skills Library\n`);
  lines.push(`The following skills define specialist knowledge.\n`);
  lines.push(`Reference the relevant skill when working on a task.\n`);

  const skills = fs.readdirSync(CORE_SKILLS_PATH);
  let count = 0;
  for (const skill of skills) {
    const fullPath = path.join(CORE_SKILLS_PATH, skill);
    if (!fs.statSync(fullPath).isDirectory()) continue;
    const section = buildSkillSection(fullPath);
    if (section) {
      lines.push(section);
      count++;
    }
  }

  // ── Write ────────────────────────────────────────────────────────────────────
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, lines.join(''));
  console.log(`Generated .github/copilot-instructions.md (${count} skills) → ${OUTPUT_FILE}`);
}

module.exports = { run };
